// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddeltijuwlqkzsaejnwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZWx0aWp1d2xxa3pzYWVqbndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzYyMzIsImV4cCI6MjA3MDg1MjIzMn0.j9h5XQeMUM_aZZ9fj2OqfPb1vqQ6AQNZakGiAMcTZ4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});